image: maven:3.9.6-eclipse-temurin-21

stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Start building"
    - docker build -t yehorka/cont-manger:3.00 /contact-manager 

deploy-job:
  stage: deploy
  sript:
    - docker compose up -d
