image: maven:3.9.6-eclipse-temurin-21

services:
  - postgres:15
variables:


stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests=false"

build-job:
  stage: build
  script:
    - echo "Start building proj"
    - cd contact-manager
    - sed -i "s|spring.datasource.url=.*|spring.datasource.url=jdbc:postgresql://postgres:5432/contact_manager|" src/main/resources/application.properties
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - contact-manager/target/*.jar

test-job:
  stage: test
  script:
    - echo "Running tests"
    - cd contact-manager
    - mvn test

