stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "Start building"
    - docker build -t yehorka/contact-manager:latest ./contact-manager 

deploy-job:
  stage: deploy
  script:
    - docker compose up -d