image: maven:3.9.6-eclipse-temurin-17

stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests=false"

build-job:
  stage: build
  script:
    - echo "Start building proj"
    - cd contact-manager
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - contact-manager/target/*.jar

test-job:
  stage: test
  script:
    - echo "Running tests"
    - cd contact-manager
    - mvn test

