stages:
  - build
  - test

variables:
  MAVEN_CLI_OPTS: "-B -DskipTests=false"
before_script:
  - export JAVA_HOME="/usr/ib/jvm/java-17-openjdk"
  - export PATH="$JAVA_HOME/bin:$PATH"



build-job:
  stage: build
  script:
    - echo "Start building proj"
    - mvn $MAVEN_CLI_OPTS clean package
  artifacts:
    paths:
      - target/*.jar

test-job:
  stage: test
  script:
    - echo "Running tests"
    - mvn test

