version: '3.8'
services:
  backend:
    image: yehorka/contact-manager:latest
    ports:
      - "8085:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contact_manager
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=dev17
  db:
    image: postgres:15
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev17
      POSTGRES_DB: contact_manager
    volumes:
      - postgres_data:/var/lib/postgresql/data 

volumes:
  postgres_data:

